# Generated by Django 5.2.8 on 2026-03-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('identifier', models.CharField(primary_key=True, serialize=False)),
                ('routestring', models.CharField()),
                ('type', models.CharField(choices=[('AMERICAN', 'AMERICAN'), ('NAT', 'NAT'), ('EUROPE', 'EUROPE')], max_length=20)),
            ],
        ),
    ]
