# Generated by GitHub Copilot on 2026-03-15

from django.db import migrations, models


LEGACY_ROUTE_TYPE_MAP = {
    'AMERICAN': 'AMAS',
    'EUROPE': 'EMEA',
    'NAT': 'NAT',
    'AMAS': 'AMAS',
    'EMEA': 'EMEA',
}


def normalize_route_type(route_type):
    return LEGACY_ROUTE_TYPE_MAP.get((route_type or '').strip().upper(), 'NAT')


def build_identifier_base(routestring):
    waypoints = [part.strip().upper() for part in (routestring or '').split() if part.strip()]
    if not waypoints:
        return ''
    return f"{waypoints[0]}_{waypoints[-1]}"


def build_unique_identifier(routestring, reserved_identifiers):
    base_identifier = build_identifier_base(routestring)
    if not base_identifier:
        return ''

    candidate = base_identifier
    suffix = 2
    while candidate in reserved_identifiers:
        candidate = f"{base_identifier}_{suffix}"
        suffix += 1
    return candidate


def migrate_routes(apps, schema_editor):
    Route = apps.get_model('routeplanner', 'Route')
    existing_routes = list(Route.objects.all().order_by('identifier'))

    route_payloads = []
    reserved_identifiers = set()
    for route in existing_routes:
        identifier = build_unique_identifier(route.routestring, reserved_identifiers)
        if not identifier:
            identifier = route.identifier
        reserved_identifiers.add(identifier)
        route_payloads.append({
            'identifier': identifier,
            'routestring': route.routestring,
            'type': normalize_route_type(route.type),
        })

    Route.objects.all().delete()
    Route.objects.bulk_create([Route(**payload) for payload in route_payloads])


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0002_route'),
    ]

    operations = [
        migrations.RunPython(migrate_routes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('AMAS', 'AMAS'), ('EMEA', 'EMEA'), ('NAT', 'NAT')], max_length=20),
        ),
    ]