# Generated by Django 5.2.8 on 2026-03-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0003_route_type_and_identifier_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airway',
            fields=[
                ('identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AirwayWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('airway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeplanner.airway')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeplanner.location')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('airway', 'order')},
            },
        ),
        migrations.AddField(
            model_name='airway',
            name='waypoints',
            field=models.ManyToManyField(related_name='airways', through='routeplanner.AirwayWaypoint', to='routeplanner.location'),
        ),
    ]
