# Generated by Django 5.2.8 on 2026-03-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0004_airway_airwaywaypoint_airway_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='waypoint_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='identifier',
            field=models.CharField(max_length=10),
        ),
    ]
