# Generated by Django 5.2.8 on 2026-03-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0007_route_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='routerevisionentry',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
