# Generated by Django 5.2.8 on 2026-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0008_route_color_routerevisionentry_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='routerevisionentry',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
