# Generated by Django 5.2.8 on 2026-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0008_route_color_routerevisionentry_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='identifier',
            field=models.CharField(db_index=True, max_length=10),
        ),
        # Functional index so case-insensitive lookups via
        # annotate(identifier_upper=Upper('identifier')).filter(identifier_upper__in=...)
        # use an index scan instead of a sequential scan on large datasets.
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS routeplanner_location_identifier_upper_idx '
                'ON routeplanner_location (UPPER(identifier));',
            reverse_sql='DROP INDEX IF EXISTS routeplanner_location_identifier_upper_idx;',
        ),
    ]
