# Generated by Django 5.2.8 on 2026-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0009_location_identifier_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Fix',
                'verbose_name_plural': 'Custom Fixes',
                'ordering': ['identifier'],
            },
        ),
    ]
